[package]
name = "qemu-rust-generator"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
# build = "build.rs"

# [build-dependencies]
# serde_codegen = "*"

[dependencies]
bytes = "*"
hyper = "*"
json = "*"
log = "*"
mio = "*"
nom = "*"
simple_logger = "*"
slab = "*"
# serde = "*"
# serde_json = "*"
