[package]
name = "qemu-rust-generator"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
bytes = "*"
hyper = "*"
log = "*"
mio = "*"
nom = "*"
simple_logger = "*"
slab = "*"
